id: P007903
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ15391
  title: ཀུན་དགའ་གྲོལ་མཆོག་བློ་གསལ་རྒྱ་མཚོའི་གསུང་འབུམ།
  author: ''
  volumes:
    980c8dc4780a4797bf9ae296eb4def20:
      image_group_id: I1KG12837
      title: Volume 1 of kun dga' grol chog blo gsal rgya mtsho'i gsung 'bum/
      volume_number: 1
      total_pages: 292
      base_file: v001.txt
    aee8f44d57cb46cfa89672a4920597c9:
      image_group_id: I1KG12838
      title: Volume 2 of kun dga' grol chog blo gsal rgya mtsho'i gsung 'bum/
      volume_number: 2
      total_pages: 431
      base_file: v002.txt
ebook_metadata:
  title: ཀུན་དགའ་གྲོལ་མཆོག་བློ་གསལ་རྒྱ་མཚོའི་གསུང་འབུམ།
  author: ''
  sku: P007903
  cover: cover.jpg
  layers:
  - pagination
