id: P007903
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ15391
  title: ཀུན་དགའ་གྲོལ་མཆོག་བློ་གསལ་རྒྱ་མཚོའི་གསུང་འབུམ།
  author: ''
  volumes:
    59025b314a634e33bd7286f59b397ebc:
      image_group_id: I1KG12837
      title: ''
      volume_number: 1
      total_pages: 292
    20236007cb3744a8ae02a594d1229d36:
      image_group_id: I1KG12838
      title: ''
      volume_number: 2
      total_pages: 431
ebook_metadata:
  title: ཀུན་དགའ་གྲོལ་མཆོག་བློ་གསལ་རྒྱ་མཚོའི་གསུང་འབུམ།
  author: ''
  sku: P007903
  cover: cover.jpg
  layers:
  - pagination
