id: I76F59BCB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:58:35+00:00'
last_modified: '2022-06-09T07:17:13.863361+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ15391
  title: ཀུན་དགའ་གྲོལ་མཆོག་བློ་གསལ་རྒྱ་མཚོའི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    226C:
      image_group_id: I1KG12837
      title: Volume 1 of kun dga' grol chog blo gsal rgya mtsho'i gsung 'bum/
      total_pages: 292
      order: 1
      base_file: 226C.txt
    C44E:
      image_group_id: I1KG12838
      title: Volume 2 of kun dga' grol chog blo gsal rgya mtsho'i gsung 'bum/
      total_pages: 431
      order: 2
      base_file: C44E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
